config/routes.rb
Rails.application.routes.draw do
  
root 'sessions#new'

  get    '/help',    to: 'static_pages#help'
  get    '/comments',    to: 'static_pages#comments'
  get    '/home',   to: 'static_pages#home'
  get    '/admin', to: 'static_pages#admin'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get   '/signup',  to: 'users#new'
  get   '/redcomment', to: 'comments#new'
  post   '/redcomment', to: 'comments#new'
  get   '/showcomment', to: 'comments#show'
  get   '/feedbacks' , to: 'feedbacks#show'

  get '/like' , to: 'comments#commit_like'

  resources :users
  resources :comments
  resources :feedbacks
  #resources :customers
  #resources :users
      #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :customers, only: [:index, :create, :show, :update, :destroy]
      resources :feedbacks, only: [:index, :create, :show, :update, :destroy]
      resources :comments, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :feedback
  belongs_to :user

  has_many :feedback
  has_many :user
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_comment, only: [:show, :update, :destroy]

  # GET /comments
  def index
    @comments = Comment.all

    render json: @comments.to_json(:include=>:user)
  end

  # GET /comments/1
  def show
    render json: @comment
  end

  # POST /comments
  def create
    @user=User.find(comment_params[:user_id])
    @feedback=Feedback.find(comment_params[:feedback_id])
    @comment = Comment.new(comment_params)

    @comment.user_id=@user.id
    @comment.feedback_id=@feedback.id

    if @comment.save
      render json: 'success'
    else
      render json: 'failed'
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      render json: @comment
    else
      render json: @comment.errors, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:comment_text, :vote_count, :feedback_id, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment=Comment.new
    @feedback = Feedback.find(params[:feedback_id])
    @pre_comment=Comment.all
    @user=User.all
  end
  def show
    @comment=Comment.find(params[:id])
  end
  def create
    ## As of now we are expectin the comments through param value 
    ## One the Feedback use the controller , need to swutch ro the comment_param

    @user=User.find(params[:user_id])
    @feedback=Feedback.find(params[:feedback_id])
    @comment=Comment.new(comment_params)

    @comment.user_id=@user.id
    @comment.feedback_id=@feedback.id

    if @comment.save
      flash.now[:success] = "Your Comment Successfully posted!"
      #redirect_to '/redcomment'
      #redirect_to :controller => '/redcomment', :action => 'new',:feedback_id => @comment.feedback_id
      redirect_back fallback_location: { action: "new", feedback_id: @comment.feedback_id }
    else
      render 'new'
    end
  end

  def get_feedback
    @feedback = Feedback.find(params[:feedback_id])
  end

  def commit_like
    @user=User.find(comment_params[:user_id])
    @feedback=Feedback.find(comment_params[:feedback_id])
    @comment=Comment.new(comment_params)

    @comment.user_id=@user.id
    @comment.feedback_id=@feedback.id

## Well, I do not have a like yet to this feedback, Please give me a chance
    if @comment.save
      redirect_back fallback_location: { action: "new", feedback_id: @comment.feedback_id }      
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.

    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:comment_text, :vote_count, :feedback_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def voted?(feedback_id,user_id)
    comm=Comment.all
      if(comm!=nil)
        comm.each do |c|
          if(c.feedback_id==feedback_id && c.user_id==user_id && c.vote_count!=nil)
            return true
          end
        end
        return false
      end
    end
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment_text %>
    <%= f.text_area :comment_text %>
  </div>

  <div class="field">
    <%= f.label :vote_count %>
    <%= f.number_field :vote_count %>
  </div>

  <div class="field">
    <%= f.label :feedback_id %>
    <%= f.text_field :feedback_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_newcommentform.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <h1><%= f.label @feedback.feedback_title %></h1>
  </div>

  <div class="field">
    <%= f.label :Feedback_Description %>
    <pre>
    <%= f.label @feedback.feedback_desc %>
    </pre>
  </div>

 <%if voted?(@feedback.id,session[:user_id])%>
    <div class="action">
    <button type="button" class="btn btn-secondary btn-lg disabled">like</button>
    </div></br>
 <%else%>
    <div class="action">
    <%= link_to "Like", like_path(:comment=> {:feedback_id => @feedback.id, :user_id => session[:user_id],:vote_count =>'1'}), class: 'btn btn-success'%>
    </div></br>
  <%end%>

  <div class="field">
    <%= f.label :comments %>
    <%@comment%>
    <pre>
      <%if @pre_comment.nil?%>
         no comments Yet..
      <%else%>
        <%@pre_comment.each do |c|%>
          <%if c.feedback_id==@feedback.id && c.comment_text!=nil%>
            <%= f.label c.comment_text%>--<%=@user.find_by_id(c.user_id.to_s).email%>
          <%end%>
        <%end%>     
      <%end%>
    </pre>
  </div>

  <div class="field">
    <%= f.label :ScreenShot %>
    <img/>
  </div>

  <div class="field">
    <%= f.label :your_comment %>
    <%= f.text_area :comment_text %>
  </div>
  <div class="field">
      <input type="hidden" class="field" name="user_id" value= <%= session[:user_id]%> />
      <input type="hidden" class="field" name="feedback_id" value= <%= @feedback.id%> />
  </div>

  <div class="btn-group">
    <%= f.submit "Post", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment text</th>
      <th>Vote count</th>
      <th>Feedback</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment_text %></td>
        <td><%= comment.vote_count %></td>
        <td><%= comment.feedback %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<%= render 'newcommentform', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Comment text:</strong>
  <%= @comment.comment_text %>
</p>

<p>
  <strong>Vote count:</strong>
  <%= @comment.vote_count %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @comment.feedback %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>