config/routes.rb
Rails.application.routes.draw do
  
root 'sessions#new'

  get    '/help',    to: 'static_pages#help'
  get    '/comments',    to: 'static_pages#comments'
  get    '/home',   to: 'static_pages#home'
  get    '/admin', to: 'static_pages#admin'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get   '/signup',  to: 'users#new'
  get   '/redcomment', to: 'comments#new'
  post   '/redcomment', to: 'comments#new'
  get   '/showcomment', to: 'comments#show'
  get   '/feedbacks' , to: 'feedbacks#show'

  get '/like' , to: 'comments#commit_like'

  resources :users
  resources :comments
  resources :feedbacks
  #resources :customers
  #resources :users
      #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :customers, only: [:index, :create, :show, :update, :destroy]
      resources :feedbacks, only: [:index, :create, :show, :update, :destroy]
      resources :comments, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
end

app/controllers/api/v1/feedbacks_controller.rb
class Api::V1::FeedbacksController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_feedback, only: [:show, :update, :destroy]

  # GET /feedbacks
  def index
    @feedbacks = Feedback.all

    render json: @feedbacks
  end

  # GET /feedbacks/1
  def show
    render json: @feedback
  end

  # POST /feedbacks
  def create
    @user=User.find_by_email(feedback_params[:email])
    @feedback = Feedback.new(feedback_params)

    @feedback.user_id=@user.id
    if @feedback.save
      render json: 'success'
    else
      render json: 'failed'
    end
  end

  # PATCH/PUT /feedbacks/1
  def update
    if @feedback.update(feedback_params)
      render json: @feedback
    else
      render json: @feedback.errors, status: :unprocessable_entity
    end
  end

  # DELETE /feedbacks/1
  def destroy
    @feedback.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def feedback_params
      params.require(:feedback).permit(:project_name, :app_name, :app_comp, :feedback_title, :feedback_desc, :screenshot,:email)
    end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
    @feedback=Feedback.new
  end
  def show
    @feedback=Feedback.all
    @comment=Comment.all
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def feedback_params
      params.require(:feedback).permit(:project_name, :app_name, :app_comp, :feedback_title, :feedback_desc, :screenshot,:email)
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
	def count_vote(fid)
		all_comm=Comment.all
		count=0
		all_comm.each do |c|
			if(c.feedback_id == fid)
				count=count+1 unless c.vote_count.nil?
			end
		end
		puts count
		count
	end
## Write all the bean getter and setter methods
	def customer_name(uid)
		if User.find_by_id(uid).customer_name.nil?
			return "NA"
		else
			User.find_by_id(uid).customer_name
		end
	end

## admin can only have some pecial previleges
	def admin?(uid)
		type=User.find_by_id(uid).user_type
		if type!=nil && type.downcase == 'admin'
			return true
		else
			return false
		end
	end

	def mail_url(f)
		"mailto:#{f.email}?Subject=Re:#{f.feedback_title}&Body=#{f.feedback_desc}"
	end

end

app/views/feedbacks/_form.html.erb
<%= form_for(feedback) do |f| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_name %>
    <%= f.text_field :project_name %>
  </div>

  <div class="field">
    <%= f.label :app_name %>
    <%= f.text_field :app_name %>
  </div>

  <div class="field">
    <%= f.label :app_comp %>
    <%= f.text_field :app_comp %>
  </div>

  <div class="field">
    <%= f.label :feedback_title %>
    <%= f.text_field :feedback_title %>
  </div>

  <div class="field">
    <%= f.label :feedback_desc %>
    <%= f.text_area :feedback_desc %>
  </div>

  <div class="field">
    <%= f.label :screenshot %>
    <%= f.text_field :screenshot %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.text_field :customer_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Project name</th>
      <th>App name</th>
      <th>App comp</th>
      <th>Feedback title</th>
      <th>Feedback desc</th>
      <th>Screenshot</th>
      <th>User</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.project_name %></td>
        <td><%= feedback.app_name %></td>
        <td><%= feedback.app_comp %></td>
        <td><%= feedback.feedback_title %></td>
        <td><%= feedback.feedback_desc %></td>
        <td><%= feedback.screenshot %></td>
        <td><%= feedback.user %></td>
        <td><%= feedback.customer %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>&nbsp</th>
      <th>Feedbacks</th>
      <th>User</th>
      <th>Customer</th>
      <th>Likes</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%@feedback.each do |f|%>
    <tr>
      <td><input type="checkbox" value=<%=f.id%>></td>
      <td><%= link_to f.feedback_title, redcomment_path(:feedback_id => f.id)%></td>
      <td><a href=<%=mail_url(f)%> title="title" ><%=f.email%></a></td>
      <td><%=customer_name(f.user_id)%></td>
      <td>
       <%=count_vote(f.id)%>
      </td>
      <td><%=image_tag("hot_images.jpg",size: "16x10") if count_vote(f.id) >=5 %></td>
    </tr>
  <%end%>  
  </tbody>
</table></br></br>
<button type="button" class="btn btn-primary">Send to Evaluate</button>&nbsp&nbsp&nbsp&nbsp&nbsp

<%if admin?(session[:user_id])%>
  <button type="button" class="btn btn-primary">Delete</button>
<%end%>