config/routes.rb
Rails.application.routes.draw do
  
root 'sessions#new'

  get    '/help',    to: 'static_pages#help'
  get    '/comments',    to: 'static_pages#comments'
  get    '/home',   to: 'static_pages#home'
  get    '/admin', to: 'static_pages#admin'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get   '/signup',  to: 'users#new'
  get   '/redcomment', to: 'comments#new'
  post   '/redcomment', to: 'comments#new'
  get   '/showcomment', to: 'comments#show'
  get   '/feedbacks' , to: 'feedbacks#show'

  get '/like' , to: 'comments#commit_like'

  resources :users
  resources :comments
  resources :feedbacks
  #resources :customers
  #resources :users
      #api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :customers, only: [:index, :create, :show, :update, :destroy]
      resources :feedbacks, only: [:index, :create, :show, :update, :destroy]
      resources :comments, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <center><small>
    <a href="http://www.siemens.com/in/en/home.html">Siemens India Website</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    © Siemens Ltd., 1996 – 2017 <a href="http://www.siemens.co.in/en/footer/index/corporate_information.htm">Corporate Information
    </a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href= 'http://www.siemens.co.in/en/footer/index/privacy_policy.htm'>Privacy Policy</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href= 'http://www.siemens.com/corp/en/index/siemens_ag_cookie_policy.htm'>Cookie Policy</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href= 'http://www.siemens.co.in/en/footer/terms_of_use.htm'>Terms of use</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
    <a href= 'http://www.siemens.com/corp/en/index/digital_id.htm'>Digital ID</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
  </small></center>
</footer>

         

app/views/layouts/_header.html.erb
    <header class='navbar navbar-fixed-top navbar-inverse'>
    	<div class='container'>
    		<%= link_to image_tag("siemens-logo-en-2x.png", :border => 0, :alt => '', :title => '', size: "300x40"), root_path,id: 'logo'%>
    		<nav>
    			<ul class="nav navbar-nav navbar-right">
    				<li><%= link_to "Help", help_path %></li>

            <% if logged_in? %>
                <li><%= link_to "Home", '/feedbacks' %></li>
               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", '#' %></li>
                  <li><%= link_to "Settings", '#' %></li>

                  <% if is_admin? %>
                    <li><%= link_to "create user", signup_path %></li>                    
                  <%end%>

                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
                  <li><%= link_to "Log in", login_path %></li>
            <% end %>

     			</ul>
    		</nav>
    	</div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim'%>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="container">
          <% flash.each do |message_type, message| %>
      	  <div class="alert alert-<%= message_type %>"><%= message %></div>
      	  <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>

      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>